function PathLogo(): React.ReactElement {
  return (
    <svg viewBox="0 0 48 48" width={36} height={36} fill="none" aria-hidden="true">
      <rect width="48" height="48" rx="8" fill="#0E2226" />
      <circle cx="24" cy="11" r="4.8" fill="#CE6A49" />
      <path d="M9 33 A 15 14 0 0 0 39 33" stroke="#F5F0EB" strokeWidth="2.6" strokeLinecap="round" fill="none" />
      <circle cx="19.5" cy="39" r="1.3" fill="#F5F0EB" />
      <circle cx="24" cy="39" r="1.3" fill="#F5F0EB" />
      <circle cx="28.5" cy="39" r="1.3" fill="#F5F0EB" />
      <line x1="13" y1="43.5" x2="35" y2="43.5" stroke="#F5F0EB" strokeWidth="1.3" strokeLinecap="round" />
    </svg>
  );
}

export default function PlanPreview(): React.ReactElement {
  return (
    <div className="plan-doc" role="region" aria-label="Action plan preview">
      <div className="plan-letterhead">
        <span className="plan-mark" aria-hidden="true"><PathLogo /></span>
        <div>
          <div className="plan-letterhead-name">TRUE Path Navigator</div>
          <div className="plan-letterhead-tag"><em>Clear pathways. Better careers.</em></div>
        </div>
        <span className="plan-letterhead-meta">Personalized career plan · v1</span>
      </div>

      <h2>From caregiving experience to RN — your path.</h2>

      <div className="plan-section">
        <h3>Your background</h3>
        <p>
          You're returning to work, available weekday evenings and weekends, and you've done
          both paid and informal caregiving. You're optimizing for steady income, predictable
          scheduling, and room to grow.
        </p>
      </div>

      <div className="plan-section">
        <h3>Recommended pathway</h3>
        <p style={{ fontFamily: 'var(--font-display)', fontSize: 22, color: 'var(--ink)' }}>
          CNA → LPN → RN
        </p>
        <p>
          A stackable nursing pathway. Begin as a CNA in 6–12 weeks; bridge into LPN within
          12–18 months; complete an ADN program in 2–3 years total. Wage range across the
          ladder: $22–$52 / hr in King County.
        </p>
      </div>

      <div className="plan-section">
        <h3>Your next three steps</h3>
        <ol className="plan-steps">
          <li>
            <span className="n">1</span>
            <div>
              <strong>Confirm WIOA eligibility with a CPS case manager.</strong>
              <span>Most short-term CNA training in King County is fundable through WIOA. Bring a photo ID and proof of income.</span>
            </div>
          </li>
          <li>
            <span className="n">2</span>
            <div>
              <strong>Apply to an evening CNA cohort at Renton Technical College or Bates Tech.</strong>
              <span>Both run rolling 6–12 week cohorts. Cost is typically waived with WIOA.</span>
            </div>
          </li>
          <li>
            <span className="n">3</span>
            <div>
              <strong>Schedule a one-hour planning call with CPS in week 4 of training.</strong>
              <span>By then you'll know if the LPN bridge fits your timeline — we'll line up clinical placements.</span>
            </div>
          </li>
        </ol>
      </div>

      <div className="plan-section">
        <h3>Support resources</h3>
        <p>
          <strong style={{ color: 'var(--ink)', fontWeight: 500 }}>Career Path Services — King County branch.</strong>
          <br />
          Eve Asbury, Workforce Navigator · (206) 555-0142 · eve.asbury@cps.org
          <br />
          Drop-in hours: Tuesdays 1–4pm, 800 5th Ave, Seattle.
        </p>
      </div>

      <div className="plan-foot">
        <strong>Sources:</strong> O*NET task data v28.1 · WA Employment Security Department wage tables (Q1 2026) · ETPL (informational only).
        <br />
        <strong>Disclaimer:</strong> Eligibility for WIOA, training programs, and licensure must be confirmed with a case manager. This plan is generated by AI and is not legal or financial advice.
      </div>
    </div>
  );
}
